- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/world/default/model/agridrone/link/camera_optical_frame/sensor/camera_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/world/default/model/agridrone/link/camera_optical_frame/sensor/camera_sensor/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/joint_states2"
  gz_topic_name: "/model/agridrone/joint/position"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/pan_tilt/joint_states"
  gz_topic_name: "/model/agridrone/joint/position"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: ROS_TO_GZ
- ros_topic_name: "/pan_joint/command"
  gz_topic_name: "/model/agridrone/joint/pan_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/tilt_joint/command"
  gz_topic_name: "/model/agridrone/joint/tilt_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
